postgres:
	docker run --name postgres -p 5432:5432 -e POSTGRES_USER=root -e POSTGRES_PASSWORD=091002 -d postgres

createdb:
	docker exec -it postgres createdb --username=root --owner=root simple_bank

dropdb:
	docker exec -it postgres dropdb simple_bank

Start:
	docker start postgres

migrateup:
	migrate -path database/migration -database "postgres://root:091002@localhost:5432/simple_bank?sslmode=disable" -verbose up

migrateup1:
	migrate -path database/migration -database "postgres://root:091002@localhost:5432/simple_bank?sslmode=disable" -verbose up 1

migratedown:
	migrate -path database/migration -database "postgres://root:091002@localhost:5432/simple_bank?sslmode=disable" -verbose down

migratedown1:
	migrate -path database/migration -database "postgres://root:091002@localhost:5432/simple_bank?sslmode=disable" -verbose down 1

sqlc:
	docker run --rm -v "$(CURDIR):/src" -w /src kjconroy/sqlc generate

sqlc-pwsh:
	docker run --rm -v "$(pwd):/src" -w /src kjconroy/sqlc generate

test:
	go test -v -cover ./database/sqlc

server:
	go run main.go
mock:
	mockgen -package mockdb -destination  database/mock/store.go github.com/October-9th/simple-bank/database/sqlc Store
.PHONY: postgres createdb dropdb migrateup migratedown sqlc test server debug migratedown1 migrateup1
