postgres12:
    docker run --name postgres12 -p 5432:5432 -e POSTGRES_USER=root -e POSTGRES_PASSWOR=0910 -d postgres:12-alpine
createdb:
    docker exec -it postgres12 createdb --username=root --owner=root simple_bank
dropdb:
    docker exec -it postgres12 dropdb simple_bank
migrateup:
    migrate -path database/migration -database "postgres://postgres:091002@localhost:5432/simple_banksslmode=disable" -verbose up
migratedown:
    migrate -path database/migration -database "postgres://postgres:091002@localhost:5432/simple_banksslmode=disable" -verbose down
sqlc:
    docker run --rm -v "$(pwd):/src" -w /src kjconroy/sqlc generate
test:
    go test -v -cover ./database/sqlc
.PHONY: createdb dropdb
