postgres:
	docker run --name simplebank --network bank-network -p 8080:8080 -e DB_SOURCE="postgres://root:091002@postgres:5432/simple_bank?sslmode=disable" simplebank:latest

network:
	docker network create bank-network

db_docs:
	dbdocs build doc/db.doml

db_schema:
	dbml2sql --postgres -o doc/schema.sql doc/db.dbml

createdb:
	docker exec -it postgres createdb --username=root --owner=root simple_bank

dropdb:
	docker exec -it postgres dropdb simple_bank

Start:
	docker start postgres

new_migration:
	migrate create -ext sql -dir db/migration -seq $(name)

migrateup:
	migrate -path database/migration -database "postgres://root:091002@localhost:5432/simple_bank?sslmode=disable" -verbose up

migrateup1:
	migrate -path database/migration -database "postgres://root:091002@localhost:5432/simple_bank?sslmode=disable" -verbose up 1

migratedown:
	migrate -path database/migration -database "postgres://root:091002@localhost:5432/simple_bank?sslmode=disable" -verbose down

migratedown1:
	migrate -path database/migration -database "postgres://root:091002@localhost:5432/simple_bank?sslmode=disable" -verbose down 1

sqlc:
	docker run --rm -v "$(CURDIR):/src" -w /src kjconroy/sqlc generate

sqlc-pwsh:
	docker run --rm -v "$(pwd):/src" -w /src kjconroy/sqlc generate

test:
	go test -v -cover ./database/sqlc

server:
	go run main.go
mock:
	mockgen -package mockdb -destination  database/mock/store.go github.com/October-9th/simple-bank/database/sqlc Store
.PHONY: postgres createdb dropdb migrateup migratedown sqlc test server debug migratedown1 migrateup1 network db_docs db_schema new_migration
