name: ci-test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.19
        id: go

      - name: Install dotenv package
        run: go get github.com/joho/godotenv/cmd/godotenv@v1.3.0

      - name: Load environment variables
        run: go run -modfile=go.mod -tags=dotenv -exec="go build ./..." main.go

      - name: Test
        run: go test -v -cover ./database/sqlc
