name: ci-test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: 091002
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Install go-lang migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.16.2/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/bin/migrate
          which migrate

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.19
        id: go

      - name: Load .env variables
        uses: falti/dotenv-action@v1.0.4

      - name: Run migration
        run: migrate -path database/migration -database "postgresql://root:091002@localhost:5432/simple_bank?sslmode=disable" -verbose up

      - name: Test
        env:
          DB_DRIVER: ${{ env.DB_DRIVER }}
          DB_SOURCE: postgresql://root:091002@localhost:5432/simple_bank?sslmode=disable
        run: go test -v -cover ./database/sqlc
