name: ci-test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.19
        id: go

      - name: Load .env variables
        uses: falti/dotenv-action@v1.0.4

      - name: Test
        env:
          DB_DRIVER: ${{ env.DB_DRIVER }}
          DB_SOURCE: ${{ env.DB_SOURCE }}
        run: go test -v -cover ./database/sqlc
